// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace t3.Migrations
{
    [DbContext(typeof(t3Context))]
    [Migration("20181119132935_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("t3.Models.Game", b =>
                {
                    b.Property<string>("gameID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("board");

                    b.Property<long>("p1_timestamp");

                    b.Property<long>("p2_timestamp");

                    b.Property<string>("player1");

                    b.Property<string>("player2");

                    b.Property<int>("turn");

                    b.Property<int>("watchers");

                    b.HasKey("gameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("t3.Models.Player", b =>
                {
                    b.Property<string>("playerID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("games");

                    b.Property<int>("mmr");

                    b.Property<string>("passcode");

                    b.Property<string>("playerName");

                    b.Property<int>("wins");

                    b.HasKey("playerID");

                    b.ToTable("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
